// SQL exercise content pools. Kept outside the Server Action file so tests can
// import and verify the pools directly; `use server` files may only export async
// functions in Next.js.
export const THEMES = [
  'Network Infrastructure Asset Inventory',
  'Cyber Security Incident Logging',
  'Active Directory Benutzerverwaltung',
  'IT-Helpdesk Ticket System',
  'Server Monitoring & Auslastung',
  'Software Lizenzverwaltung',
  'Backup- und Restore-Planung',
  'Patch-Management Rollout',
  'Datenschutz-Auskunftsanfragen',
  'Hardware-Beschaffung und Inventur',
  'Cloud-Kostenstellen Monitoring',
  'VPN-Zugriffsprotokolle',
  'DHCP-Lease Verwaltung',
  'DNS-Zonenpflege',
  'Firewall-Regel Audit',
  'Schulungs- und Zertifikatsverwaltung',
  'Projektzeiten im IT-Team',
  'Service-Level-Agreement Reporting',
  'Raum- und Arbeitsplatzverwaltung',
  'Wartungsverträge und Laufzeiten',
  'Energieverbrauch im Rechenzentrum',
  'Change-Request Freigaben',
] as const;

export const SQL_CONCEPTS = [
  'SELECT mit WHERE Bedingung und ORDER BY',
  'INNER JOIN zwischen zwei Tabellen',
  'GROUP BY mit HAVING Klausel',
  'INSERT INTO mit mehreren Werten',
  'UPDATE mit Bedingung',
  'DELETE mit WHERE Klausel',
  'COUNT, SUM, AVG Aggregation',
  'Subquery mit IN Operator',
  'LEFT JOIN mit IS NULL Prüfung',
  'DISTINCT und LIMIT',
  'BETWEEN für Datumsbereiche',
  'LIKE Suche mit Platzhaltern',
  'CASE WHEN für berechnete Kategorien',
  'COALESCE für NULL-Ersatzwerte',
  'ORDER BY mit mehreren Spalten',
  'MIN und MAX Aggregation',
  'NOT EXISTS Anti-Join',
  'UNION zwischen kompatiblen Abfragen',
  'ALTER TABLE ADD COLUMN',
  'CREATE INDEX für häufige Filter',
  'FOREIGN KEY Beziehung prüfen',
  'DATE_TRUNC für Monatsauswertung',
] as const;
